# Generated by gallery/generate.py; do not edit.
function arseng_gallery:clear
# me-source-jar-north: empty ME Source Jar facing north
setblock 176 100 176 arseng:me_source_jar[facing=north,waterlogged=false]
# me-source-jar-east: empty ME Source Jar facing east
setblock 180 100 176 arseng:me_source_jar[facing=east,waterlogged=false]
# me-source-jar-south: empty ME Source Jar facing south
setblock 184 100 176 arseng:me_source_jar[facing=south,waterlogged=false]
# me-source-jar-west: empty ME Source Jar facing west
setblock 188 100 176 arseng:me_source_jar[facing=west,waterlogged=false]
# source-acceptor-control: ME Source Converter stock-model control
setblock 192 100 176 arseng:source_acceptor
# cable-source-acceptor-down: cable source acceptor on down
setblock 176 100 180 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},down:{id:"arseng:cable_source_acceptor"}}
# cable-source-acceptor-up: cable source acceptor on up
setblock 180 100 180 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},up:{id:"arseng:cable_source_acceptor"}}
# cable-source-acceptor-north: cable source acceptor on north
setblock 184 100 180 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},north:{id:"arseng:cable_source_acceptor"}}
# cable-source-acceptor-south: cable source acceptor on south
setblock 188 100 180 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},south:{id:"arseng:cable_source_acceptor"}}
# cable-source-acceptor-west: cable source acceptor on west
setblock 192 100 180 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},west:{id:"arseng:cable_source_acceptor"}}
# cable-source-acceptor-east: cable source acceptor on east
setblock 196 100 180 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},east:{id:"arseng:cable_source_acceptor"}}
# source-p2p-tunnel-down: source p2p tunnel on down
setblock 176 100 184 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},down:{id:"arseng:source_p2p_tunnel"}}
# source-p2p-tunnel-up: source p2p tunnel on up
setblock 180 100 184 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},up:{id:"arseng:source_p2p_tunnel"}}
# source-p2p-tunnel-north: source p2p tunnel on north
setblock 184 100 184 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},north:{id:"arseng:source_p2p_tunnel"}}
# source-p2p-tunnel-south: source p2p tunnel on south
setblock 188 100 184 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},south:{id:"arseng:source_p2p_tunnel"}}
# source-p2p-tunnel-west: source p2p tunnel on west
setblock 192 100 184 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},west:{id:"arseng:source_p2p_tunnel"}}
# source-p2p-tunnel-east: source p2p tunnel on east
setblock 196 100 184 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},east:{id:"arseng:source_p2p_tunnel"}}
# spell-p2p-tunnel-down: spell p2p tunnel on down
setblock 176 100 188 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},down:{id:"arseng:spell_p2p_tunnel"}}
# spell-p2p-tunnel-up: spell p2p tunnel on up
setblock 180 100 188 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},up:{id:"arseng:spell_p2p_tunnel"}}
# spell-p2p-tunnel-north: spell p2p tunnel on north
setblock 184 100 188 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},north:{id:"arseng:spell_p2p_tunnel"}}
# spell-p2p-tunnel-south: spell p2p tunnel on south
setblock 188 100 188 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},south:{id:"arseng:spell_p2p_tunnel"}}
# spell-p2p-tunnel-west: spell p2p tunnel on west
setblock 192 100 188 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},west:{id:"arseng:spell_p2p_tunnel"}}
# spell-p2p-tunnel-east: spell p2p tunnel on east
setblock 196 100 188 ae2:cable_bus{hasRedstone:2,cable:{id:"ae2:fluix_glass_cable"},east:{id:"arseng:spell_p2p_tunnel"}}
# source-cell-drive: AE2 Drive with all five Source Storage Cells
setblock 176 100 192 ae2:drive[facing=south,spin=0]
data merge block 176 100 192 {inv:{item0:{id:"arseng:source_storage_cell_1k",count:1},item1:{id:"arseng:source_storage_cell_4k",count:1},item2:{id:"arseng:source_storage_cell_16k",count:1},item3:{id:"arseng:source_storage_cell_64k",count:1},item4:{id:"arseng:source_storage_cell_256k",count:1},item5:{},item6:{},item7:{},item8:{},item9:{}}}
# stock-control: stone stock rendering control
setblock 180 100 192 minecraft:stone
function arseng_gallery:verify
