# Generated by gallery/generate.py; do not edit.
execute unless block 176 100 176 arseng:me_source_jar[facing=north,waterlogged=false] run tellraw @a {"text":"gallery mismatch: me-source-jar-north","color":"red"}
execute unless block 180 100 176 arseng:me_source_jar[facing=east,waterlogged=false] run tellraw @a {"text":"gallery mismatch: me-source-jar-east","color":"red"}
execute unless block 184 100 176 arseng:me_source_jar[facing=south,waterlogged=false] run tellraw @a {"text":"gallery mismatch: me-source-jar-south","color":"red"}
execute unless block 188 100 176 arseng:me_source_jar[facing=west,waterlogged=false] run tellraw @a {"text":"gallery mismatch: me-source-jar-west","color":"red"}
execute unless block 192 100 176 arseng:source_acceptor run tellraw @a {"text":"gallery mismatch: source-acceptor-control","color":"red"}
execute unless block 176 100 180 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: cable-source-acceptor-down","color":"red"}
execute unless block 180 100 180 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: cable-source-acceptor-up","color":"red"}
execute unless block 184 100 180 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: cable-source-acceptor-north","color":"red"}
execute unless block 188 100 180 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: cable-source-acceptor-south","color":"red"}
execute unless block 192 100 180 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: cable-source-acceptor-west","color":"red"}
execute unless block 196 100 180 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: cable-source-acceptor-east","color":"red"}
execute unless block 176 100 184 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: source-p2p-tunnel-down","color":"red"}
execute unless block 180 100 184 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: source-p2p-tunnel-up","color":"red"}
execute unless block 184 100 184 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: source-p2p-tunnel-north","color":"red"}
execute unless block 188 100 184 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: source-p2p-tunnel-south","color":"red"}
execute unless block 192 100 184 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: source-p2p-tunnel-west","color":"red"}
execute unless block 196 100 184 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: source-p2p-tunnel-east","color":"red"}
execute unless block 176 100 188 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: spell-p2p-tunnel-down","color":"red"}
execute unless block 180 100 188 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: spell-p2p-tunnel-up","color":"red"}
execute unless block 184 100 188 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: spell-p2p-tunnel-north","color":"red"}
execute unless block 188 100 188 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: spell-p2p-tunnel-south","color":"red"}
execute unless block 192 100 188 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: spell-p2p-tunnel-west","color":"red"}
execute unless block 196 100 188 ae2:cable_bus run tellraw @a {"text":"gallery mismatch: spell-p2p-tunnel-east","color":"red"}
execute unless block 176 100 192 ae2:drive[facing=south,spin=0] run tellraw @a {"text":"gallery mismatch: source-cell-drive","color":"red"}
execute unless block 180 100 192 minecraft:stone run tellraw @a {"text":"gallery mismatch: stock-control","color":"red"}
tellraw @a {"text":"Ars Énergistique gallery checked","color":"green"}
